"""
memory/memory_store.py
-----------------------
Pillar 4B: Cross-session long-term memory.

Stores embeddings of completed analysis sessions so future queries
can retrieve relevant past context before the Orchestrator begins work.

Backend priority:
  1. ChromaDB (vector store) — semantic similarity search. Requires
     `chromadb` and `sentence-transformers` to be installed.
  2. JSON file fallback — simple keyword search in a flat JSON log.
     Used automatically if ChromaDB is not available.
"""

from __future__ import annotations

import json
import os
import hashlib
from typing import Optional
from datetime import datetime

# ── Constants ──────────────────────────────────────────────────────────────────

_MEMORY_DIR   = os.path.join(os.path.dirname(__file__))
_JSON_STORE   = os.path.join(_MEMORY_DIR, "memory_store.json")
_CHROMA_DIR   = os.path.join(_MEMORY_DIR, "chroma_db")
_COLLECTION   = "mas_sessions"
_TOP_K        = 3   # how many past sessions to retrieve


# ── Backend Detection ──────────────────────────────────────────────────────────

def _chromadb_available() -> bool:
    try:
        import chromadb  # noqa
        import sentence_transformers  # noqa
        return True
    except ImportError:
        return False


# ── ChromaDB Backend ───────────────────────────────────────────────────────────

def _get_chroma_collection():
    import chromadb
    from sentence_transformers import SentenceTransformer
    client = chromadb.PersistentClient(path=_CHROMA_DIR)
    collection = client.get_or_create_collection(
        name=_COLLECTION,
        metadata={"hnsw:space": "cosine"},
    )
    return client, collection


def _chroma_save(task: str, answer: str, urls: list[str]) -> None:
    _, collection = _get_chroma_collection()
    doc_id = hashlib.md5(f"{task}{datetime.now().isoformat()}".encode()).hexdigest()
    document = f"TASK: {task}\nANSWER: {answer}"
    collection.add(
        documents=[document],
        metadatas=[{
            "task":      task[:200],
            "answer":    answer[:500],
            "urls":      json.dumps(urls[:5]),
            "timestamp": datetime.now().isoformat(),
        }],
        ids=[doc_id],
    )


def _chroma_search(query: str, top_k: int = _TOP_K) -> list[dict]:
    _, collection = _get_chroma_collection()
    if collection.count() == 0:
        return []
    results = collection.query(
        query_texts=[query],
        n_results=min(top_k, collection.count()),
    )
    memories = []
    for i, meta in enumerate(results["metadatas"][0]):
        memories.append({
            "task":      meta.get("task", ""),
            "answer":    meta.get("answer", ""),
            "urls":      json.loads(meta.get("urls", "[]")),
            "timestamp": meta.get("timestamp", ""),
            "distance":  results["distances"][0][i] if results.get("distances") else None,
        })
    return memories


# ── JSON Fallback Backend ──────────────────────────────────────────────────────

def _json_load() -> list[dict]:
    if not os.path.exists(_JSON_STORE):
        return []
    with open(_JSON_STORE, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def _json_save(task: str, answer: str, urls: list[str]) -> None:
    store = _json_load()
    store.append({
        "task":      task,
        "answer":    answer[:500],
        "urls":      urls[:5],
        "timestamp": datetime.now().isoformat(),
    })
    # Keep only last 100 entries to prevent unbounded growth
    store = store[-100:]
    with open(_JSON_STORE, "w", encoding="utf-8") as f:
        json.dump(store, f, indent=2, ensure_ascii=False)


def _json_search(query: str, top_k: int = _TOP_K) -> list[dict]:
    store = _json_load()
    query_words = set(query.lower().split())
    scored = []
    for entry in store:
        task_words = set(entry.get("task", "").lower().split())
        overlap = len(query_words & task_words)
        if overlap > 0:
            scored.append((overlap, entry))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [entry for _, entry in scored[:top_k]]


# ── Public API ─────────────────────────────────────────────────────────────────

def save_session(task: str, answer: str, urls: Optional[list[str]] = None) -> str:
    """
    Persist a completed session to long-term memory.
    
    Args:
        task:   The original user task string.
        answer: The final answer generated by the orchestrator.
        urls:   List of URLs that were scraped during the session.
        
    Returns:
        A string indicating which backend was used ('chromadb' or 'json').
    """
    urls = urls or []
    if _chromadb_available():
        try:
            _chroma_save(task, answer, urls)
            return "chromadb"
        except Exception:
            pass  # Fall through to JSON
    _json_save(task, answer, urls)
    return "json"


def recall_similar(query: str, top_k: int = _TOP_K) -> list[dict]:
    """
    Search long-term memory for sessions similar to the current query.
    
    Args:
        query: The current user task or search query.
        top_k: Maximum number of memories to return.
        
    Returns:
        List of past session dicts: {task, answer, urls, timestamp}.
        Empty list if no relevant memories are found.
    """
    if _chromadb_available():
        try:
            results = _chroma_search(query, top_k)
            if results:
                return results
        except Exception:
            pass  # Fall through to JSON
    return _json_search(query, top_k)


def memory_backend() -> str:
    """Returns the name of the active memory backend."""
    return "chromadb" if _chromadb_available() else "json"
